// GENERATED by tools/gen-ids.ts. Do not edit.

export interface World {
  pawelek: InstanceType<typeof import("./characters/pawelek.ts").default>;
  barbarasHouse: InstanceType<typeof import("./locations/barbaras-house.ts").default>;
  pawelekFallsIll: InstanceType<typeof import("./events/pawelek-falls-ill.ts").default>;
  penicillin: InstanceType<typeof import("./items/penicillin.ts").default>;
  babcia: InstanceType<typeof import("./stubs.ts").Babcia>;
  barbara: InstanceType<typeof import("./stubs.ts").Barbara>;
  hag: InstanceType<typeof import("./stubs.ts").Hag>;
  matrona: InstanceType<typeof import("./stubs.ts").Matrona>;
  neighbour: InstanceType<typeof import("./stubs.ts").Neighbour>;
  oldVillageRuins: InstanceType<typeof import("./stubs.ts").OldVillageRuins>;
  pgrFarm: InstanceType<typeof import("./stubs.ts").PgrFarm>;
  pgrOffice: InstanceType<typeof import("./stubs.ts").PgrOffice>;
  theFlood: InstanceType<typeof import("./stubs.ts").TheFlood>;
  theStore: InstanceType<typeof import("./stubs.ts").TheStore>;
  wujas: InstanceType<typeof import("./stubs.ts").Wujas>;
}
