// Writes ids.generated.ts: the typed World (one property per entity, typed as its class). Built from
// declarations only, so a misspelt reference fails the type check.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadWorld, ROOT } from "./load.ts";

const w = await loadWorld();

const union = (name: string, ids: string[]) => {
  const uniq = [...new Set(ids)].sort();
  const body = uniq.length ? uniq.map((i) => `  | ${JSON.stringify(i)}`).join("\n") : "  never";
  return `export type ${name} =\n${body};\n`;
};

const worldProps = w.entities
  .map((e) => `  ${e.key}: InstanceType<typeof import(${JSON.stringify(e.module)}).${e.exportName}>;`)
  .join("\n");

const out = [
  "// GENERATED by tools/gen-ids.ts. Do not edit.\n",
  `export interface World {\n${worldProps}\n}\n`,
].join("\n");

writeFileSync(join(ROOT, "ids.generated.ts"), out);
console.log(`ids: ${Object.keys(w.clues).length} clues, ${w.entities.length} entities`);
